name: Docker build & Publish

on:
  push:
    branches:
      - master

jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Docker image
          run: docker build -t erubeyromero/virueladelmono:${{ github.sha }} .

        - name: Tag Docker image
          run: docker tag erubeyromero/virueladelmono:${{ github.sha }} erubeyromero/virueladelmono:latest

        - name: Push Docker image
          run: |
            docker push erubeyromero/virueladelmono:${{ github.sha }}
            docker push erubeyromero/virueladelmono:latest

